name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Updated to Node.js 18
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test || true
      
    - name: Generate deployment package
      run: zip -r deploy.zip . -x "*.git*" "node_modules/*" ".github/*" ".env*"
      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: otg-prod # Update with your app name
        environment_name: otg-prod-env
        region: eu-north-1  # Change to your region if different
        version_label: v${{ github.run_number }}-${{ github.sha | slice: 0, 7 }}
        deployment_package: deploy.zip- name: Set up Node.js
  uses: actions/setup-node@v3
  with:
    node-version: '18'
    cache: 'npm'

- name: Install dependencies
  run: npm ci --cache-min 999999

- name: Run tests
  run: npm test || true

- name: Generate deployment package
  run: zip -r deploy.zip . -x "*.git*" "node_modules/*" ".github/*" ".env*" && echo "Generated deployment package"

- name: Deploy to EB
  uses: einaregilsson/beanstalk-deploy@v21
  with:
    aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
    aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    application_name: otg-eb-pro
    environment_name: otg-eb-prod-env
    region: eu-north-1
    version_label: v${{ github.run_number }}-${{ github.sha | slice: 0, 7 }}
    deployment_package: deploy.zip